name: Build and deploy slides to GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] 

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          npm install
          npm run bundle
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./bundled 